In [11]:
import numpy as np

In [2]:
# 1 covert 1d into 2d array
a = np.array([1, 2, 3, 4, 5, 6])
a2 = a.reshape(2, 3)
print(a2)

[[1 2 3]
 [4 5 6]]


In [3]:
# 2 print array attributes 
a = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", a.shape)
print("Data type:", a.dtype)
print("Number of dimensions:", a.ndim)
print("Size:", a.size)

Shape: (2, 3)
Data type: int64
Number of dimensions: 2
Size: 6


In [4]:
# create a 3X3 numpy array of all 9 
a = np.full((3, 3), 9)
print(a)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [6]:
# 4 cereate a 1d array of 10 evenly spaced values between 25 and 125
a = np.linspace(25,125,10)
print(a)

[ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]


In [7]:
# 5 convert a python list into numpy array 
list = [10,20,30,40,50]
a = np.array(list)
print(a)

[10 20 30 40 50]


In [9]:
# 6 reverse a 1d numpy array 
a = np.array([1,2,3,4,5,6,7])
a = a[::-1]
print(a)

[7 6 5 4 3 2 1]


In [15]:
# create a 4x4x3 array and extract value at second set,
#first row and last row

from numpy import reshape


a = np.arange(48).reshape(4,4,3)
print(a)
print(a[1,0,-1])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]
14


In [16]:
# 8 create a 4X4 array and extract odd rows and even columns 
a = np.arange(1,17).reshape(4,4)
print("Original arrary:\n",a)

result = a[0::2,1::2]
print("Extracted odd rows and even columns:\n",result)

Original arrary:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Extracted odd rows and even columns:
 [[ 2  4]
 [10 12]]


In [17]:
# 9 slice first two row and firt two column ogf second set from a 4x4x3 array
a = np.arange(48).reshape(4,4,3)
result = a[1,:2,:2]
print(result)

[[12 13]
 [15 16]]


In [18]:
# 10 replace all odd number with -1 using for loop
a = np.array([[23,65,76,93],
              [71,82,13,24]])
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        if a[i,j] % 2 != 0:
            a[i,j] = -1
print(a)

[[-1 -1 76 -1]
 [-1 82 -1 24]]


In [19]:
# 11. get indices of non-zero elements
a = np.array([1,0,2,0,3,0,4])
indices = np.nonzero(a)
print("Indices of non-zero elements:", indices)

Indices of non-zero elements: (array([0, 2, 4, 6]),)


In [20]:
# 12 add two numpy array elments by element
a = np.array([1,2,3])
b = np.array([4,5,6])
result = a + b
print(result)

[5 7 9]


In [21]:
# 13 multiply two numpy array elemnts by element
a = np.array([1,2,3])
b = np.array([4,5,6])
result = a * b
print(result)

[ 4 10 18]


In [23]:
# 14 compute dot product of two numpy array
a = np.array([15,20,25])
b = np.array([10,40,37])
result = np.dot(a, b)
print(result)

1875
