In [1]:
import numpy as np

In [3]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
res = np.concatenate((a,b), axis=1)
print(res)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
a = np.arange(9)
print(a)
result = np.split(a, 3)# here 3 is no. of elements in each splited array
print(result)

for i, a in enumerate(result):
    print("Splited array", i+1)
    print(a)
    

[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
Splited array 1
[0 1 2]
Splited array 2
[3 4 5]
Splited array 3
[6 7 8]


In [9]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)

# resizing the array
a.resize((3, 2))
print(a)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]


In [17]:
a = np.array([[1, 2, 3], [4, 5, 6]])

res = np.append(a, [[7, 8,9]], axis=0)
print(res)
print("_________________")
res = np.insert(a, 1, [[10,11,12]], axis=0)
print(res)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
_________________
[[ 1  2  3]
 [10 11 12]
 [ 4  5  6]]


In [21]:
a = np.arange(12).reshape(3, 4)
print(a,"\n")
print(np.delete(a,6),"\n")
res = np.flip(a)
print(res)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[ 0  1  2  3  4  5  7  8  9 10 11] 

[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


In [26]:
a = np.array([58,91,12,32,48,10,75,63,84,29])
res = np.sort(a)
print(res)

res = np.argmin(a)
print(res)

res = a[-1::-1]
print(res)

[10 12 29 32 48 58 63 75 84 91]
5
[29 84 63 75 10 48 32 12 91 58]


In [36]:
a = np.array([[15, 27, 22], [19, 15, 5]])
b = np.array([[7, 8, 9], [4, 5, 2]])
res = a % b
print(res)

[[1 3 4]
 [3 0 1]]
