In [1]:
import pandas as pd
import numpy as np

In [ ]:
# QUES 1) Combining a one and a two-dimensional NumPy Array
array1= np.array([1, 2, 3, 4, 5])
array2= np.array([[6, 7, 8], [9, 10, 11]])

combined_array= np.concatenate((array1, array2.flatten()))
print("Combined Array:")
print(combined_array)

Combined Array:
[ 1  2  3  4  5  6  7  8  9 10 11]


In [4]:
# QUES 2) Flatten a 2d numpy array into 1d array
a = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = a.flatten()
print("Flattened Array:")
print(flattened_array)

Flattened Array:
[1 2 3 4 5 6]


In [5]:
# QUES 3) Reverse a numpy array
b = np.array([1, 2, 3, 4, 5])
reversed_array = b[::-1]
print("Reversed Array:")
print(reversed_array)


Reversed Array:
[5 4 3 2 1]


In [12]:
# QUES 4 performing array operations
a = np.array([71, 84, 63, 90, 91])
print("Maximum value in array a is:", np.max(a))
print("Minimum value in array a is:", np.min(a))

print("-------------------------")
# find shape of the array
arr = np.array([
    [1, 2],
    [4, 5],
    [7, 8]
])

rows, cols = arr.shape

print("Rows:", rows)
print("Columns:", cols)

print("-------------------------")

# accessing each element of the array
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

for row in arr:
    for element in row:
        print(element)

print("-------------------------")
# accessing specific element
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("First element:", arr[0, 0])
print("50 =", arr[1, 1])
print("60 =", arr[1, 2])

print("-------------------------")
# finding sum of 2d array
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

total = 0

for row in arr:
    for element in row:
        total += element

print("Sum =", total)

print("-------------------------")

# arithemetic operations on 2 array
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("\nAddition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Maximum value in array a is: 91
Minimum value in array a is: 63
-------------------------
Rows: 3
Columns: 2
-------------------------
10
20
30
40
50
60
-------------------------
First element: 10
50 = 50
60 = 60
-------------------------
Sum = 21
-------------------------

Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]


In [13]:
# QUES 5) Iterate 3D array using for loop and nditer 
arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("Elements using nditer:")

for element in np.nditer(arr):
    print(element)

Elements using nditer:
1
2
3
4
5
6
7
8


In [14]:
# QUES 6
arr1 = np.array([3, 4]) 
arr2 = np.array([1, 0])
print("First Array:", arr1)
print("Second Array:", arr2)

avg = (arr1 + arr2) / 2
print("\nAverage of Arrays:")
print(avg)
print("-------------------------")
arr1 = np.array([[10, 20],
                 [30, 40]])
arr2 = np.array([[50, 60],
                 [70, 80]])
print("First 2D Array:")
print(arr1)
print("\nSecond 2D Array:")
print(arr2)

avg = (arr1 + arr2) / 2
print("\nAverage of Arrays:")
print(avg)

print("------------------")
from statistics import mode
combined = np.concatenate((arr1, arr2))

print("Mean:", np.mean(combined))
print("Median:", np.median(combined))
print("Mode:", mode(combined.flatten()))

First Array: [3 4]
Second Array: [1 0]

Average of Arrays:
[2. 2.]
-------------------------
First 2D Array:
[[10 20]
 [30 40]]

Second 2D Array:
[[50 60]
 [70 80]]

Average of Arrays:
[[30. 40.]
 [50. 60.]]
------------------
Mean: 45.0
Median: 45.0
Mode: 10
