In [2]:
import numpy as np 
import pandas as pd

In [9]:
a = np.random.rand()
print("Random number:", a)

print("-------------------")
b = np.random.rand(2,3)
print("Random 2d array:\n", b)

print("-------------------")
c = np.random.rand(2,2,2)
print("Random 3d array:\n",c)

Random number: 0.7214749462235878
-------------------
Random 2d array:
 [[0.155569   0.35462464 0.1180116 ]
 [0.41023463 0.99836689 0.65876656]]
-------------------
Random 3d array:
 [[[0.61535122 0.63208139]
  [0.96757229 0.67038913]]

 [[0.6756678  0.46215076]
  [0.56580939 0.01582583]]]


In [12]:
a = np.empty([3,2])
print(a)

[[0.155569   0.35462464]
 [0.1180116  0.41023463]
 [0.99836689 0.65876656]]


In [13]:
a = np.full((3,4),0)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
print("ADD:", a[3]+a[7])

ADD: 12


In [15]:
a = np.array([[1, 2, 3, 4, 5, 6],
               [7, 8, 9, 10, 11, 12]])

print(a[1,2])


9


In [21]:
a = np.array([
   [[1, 2, 3],
         [4, 5, 6]], 
   [[7, 8, 9],
         [10,11,12]],
   [[13,14,15],
         [16,17,18]]])
print(a[1,0,2])

9


In [28]:
a = np.array([1, 2, 3, 4, 5])
print(a[0:3:2])

print("-------------------")
a = np.array([[1,2,3,4,5],[3,4,5,6,7],[5,6,7,8,9]])
print(a[0:3:2,0:4:1])

print("-------------------")
a = np.array([
   [[1, 2, 3],
         [4, 5, 6]], 
   [[7, 8, 9],
         [10,11,12]],
   ])

print(a[0:3:2,0:2:1,0:3:2])

[1 3]
-------------------
[[1 2 3 4]
 [5 6 7 8]]
-------------------
[[[1 3]
  [4 6]]]


In [36]:
a = np.array([
    [[1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]],
    [[13,14,15,16],
    [17,18,19,20],
    [21,22,23,24]],
])

print(a)
print(a.shape)

b = np.zeros((2,2,2))
print("---------------")
print(b)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
(2, 3, 4)
---------------
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [47]:
# copy vs view
a = np.array([1,2,3,4,5,6,7,8])
x=a.copy()
x[0]=100
print(x)
print(a)# value of a is no changed

print("---------------")
y = a.view()
y[2]=800
print(y)
print(a) # value of a is changed

print("---------------")
print(a.reshape(4,2))


[100   2   3   4   5   6   7   8]
[1 2 3 4 5 6 7 8]
---------------
[  1   2 800   4   5   6   7   8]
[  1   2 800   4   5   6   7   8]
---------------
[[  1   2]
 [800   4]
 [  5   6]
 [  7   8]]


In [52]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(a.reshape(6, 2))

b = np.array([1,2,3,4],ndmin=5)
print(b)
print(b.shape)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


In [53]:
a = np.array([[1, 2, 3, 4],[ 5, 6, 7, 8]])
print(np.sqrt(a))

[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]]
