In [9]:
import pandas as pd
import numpy as np

In [ ]:
# QUES 1 Replace Nan with 0 and Interchange 3 rows and 3 columns of 2D array [[6, -8, 73, -110], [np.nan, -8, 0, 94]] 
a = np.array([[6, -8, 73, -110], [np.nan, -8, 0, 94]])
a[np.isnan(a)] = 0
print(a,"\n")

a = a.T
print(a)


[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]
[[   6.    0.]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]


In [7]:
# QUES 2 Move axes of 3D array to new positions
arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(arr,"\n")
print(arr.shape)
print("-----------------------------")
moved = np.moveaxis(arr,0,2)
print(moved,"\n")
print(moved.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 

(2, 2, 2)
-----------------------------
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]] 

(2, 2, 2)


In [14]:
# QUES 3) Replace NaN values with average of columns
arr = pd.read_csv("tips.csv")
print(arr,"\n")

x = arr["total_bill"].mean()
arr.fillna({'total_bill': x,'time':'-'}, inplace=True)
print(arr)

     total_bill   tip     sex smoker   day    time  size
0           NaN  1.01  Female     No   Sun  Dinner     2
1           NaN  1.66    Male     No   Sun  Dinner     3
2           NaN  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns] 

     total_bill   tip     sex smoker   day    time  size
0      19.83166  1.01  Female     No   Sun  Dinner     2
1      19.83166  1.66    Male     No   Sun  Dinner     3
2      19.83166  3.50    Male     No   Sun  Dinner     3
3      23.68000  3.31    Male     No   Sun  Dinner     2
4    

In [15]:
# QUES 4) Replace negative value with zero in numpy array using replace function
arr = np.array([[1, -2, 3], [-4, 5, -6]])
print(arr,"\n")
arr[arr < 0] = 0
print(arr)

[[ 1 -2  3]
 [-4  5 -6]] 

[[1 0 3]
 [0 5 0]]
