In [1]:
import numpy as np


In [2]:
print(np.__version__)


2.4.6


In [3]:
a = np.array([[1,2],[3,4],[5,6],[7,8]])
print(a, type(a), a.dtype)

[[1 2]
 [3 4]
 [5 6]
 [7 8]] <class 'numpy.ndarray'> int64


In [4]:
a = np.array(
    ["aa","bb","cc"]
)
print(a.dtype)

<U2


In [6]:
a = np.array(
    ["aa","bb","cc"],dtype="S"
)
print(a.dtype)

|S2


In [13]:
a = np.zeros(5)
print(a, a.dtype)

b = np.ones([3,2,4])
print(b)

[0. 0. 0. 0. 0.] float64
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [16]:
x = np.arange(5,10,2)
print(x)

[5 7 9]
