In [1]:
import numpy as np

In [5]:
a = np.array([1, 2, 3, 4, 5, 6])
a[1],a[4],a[0] = a[4],a[1],a[3]
print(a)

[4 5 3 4 2 6]


In [10]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,22,33,44,55]])
print(a,"\n")

a[[0,2],:] = a[[2,0],:]
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 22 33 44 55]] 

[[11 22 33 44 55]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [12]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,22,33,44,55]])
print(a,"\n")
# a[rows,column]
a[:,[1,3]] = a[:,[3,1]]
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 22 33 44 55]] 

[[ 1  4  3  2  5]
 [ 6  9  8  7 10]
 [11 44 33 22 55]]


In [13]:
a = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]

])

print(a)
a[[],:,:] = a[[],:,:]


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [ ]:
a = np.array(
    [1,2,np.nan,5,np.nan,8]
)

res = np.nan_to_num(a,nan = 0)
print(a)
print(res)

[ 1.  2. nan  5. nan  8.]
[1. 2. 0. 5. 0. 8.]


In [15]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
np.save("data.npy",a)

In [16]:
res = np.load("data.npy")
print(res)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [18]:
a = np.array([1,2,3,4])
b = np.array([[5,6,7,8],[10,20,30,40]])
np.savez("data.npz",arr1=a,arr2=b)


In [21]:
data = np.load("data.npz")
print("array1:",data["arr1"])

array1: [1 2 3 4]


In [23]:
with open('data.txt','w') as f:
    f.write("1.0 2.0 3.0\n4.0 5.0 6.0\n7.0 8.0 9.0")

    data = np.loadtxt('data.txt',dtype=float)
print(data)

[]


C:\Users\smile\AppData\Local\Temp\ipykernel_13048\2814652393.py:4: UserWarning: loadtxt: input contained no data: "data.txt"
  data = np.loadtxt('data.txt',dtype=float)


In [24]:
a1 = np.array([[3,2],[1,2]])
a2 = np.array([5,5])

a1_inv = np.linalg.inv(a1)
res = np.dot(a1_inv,a2)
print(res)

[4.4408921e-16 2.5000000e+00]
